# version: ""
services:
  app:
    build: .
    container_name: django-app-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=admin
      - DB_PASS=admin123
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
