name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build containers
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm app sh -c "flake8"

      - name: Run flake8 lint (optional)
        run: docker compose run --rm app sh -c "flake8"
      - name: Run Django tests
        run: docker compose run --rm app sh -c "python manage.py test"
